export const CART_ADD_ITEM = 'CART_ADD_ITEM_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADD_ITEMRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_ITEM_RESET = 'CART_ITEM_RESET'

export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'
export const CART_ADD_ITEM_RESET = 'CART_ADD_ITEM_RESET'

export const CART_DETAILS_REQUEST = 'CART_DETAILS_REQUEST'
export const CART_DETAILS_SUCCESS = 'CART_DETAILS_SUCCESS'
export const CART_DETAILS_FAIL = 'CART_DETAILS_FAIL'

export const CART_UPDATE_ITEM_REQUEST = 'CART_UPDATE_ITEM_REQUEST'
export const CART_UPDATE_ITEM_SUCCESS = 'CART_UPDATE_ITEM_SUCCESS'
export const CART_UPDATE_ITEM_FAIL = 'CART_UPDATE_ITEM_FAIL'
export const CART_UPDATE_ITEM_RESET = 'CART_UPDATE_ITEM_RESET'

export const CART_DELETE_ITEM_REQUEST = 'CART_DELETE_ITEM_REQUEST'
export const CART_DELETE_ITEM_SUCCESS = 'CART_DELETE_ITEM_SUCCESS'
export const CART_DELETE_ITEM_FAIL = 'CART_DELETE_ITEM_FAIL'

export const CART_LIST_MY_REQUEST = 'CART_LIST_MY_REQUEST'
export const CART_LIST_MY_SUCCESS = 'CART_LIST_MY_SUCCESS'
export const CART_LIST_MY_FAIL = 'CART_LIST_MY_FAIL'
export const CART_LIST_MY_RESET = 'CART_UPDATE_ITEM_RESET'
