export const FARMER_LIST_REQUEST = 'FARMER_LIST_REQUEST'
export const FARMER_LIST_SUCCESS = 'FARMER_LIST_SUCCESS'
export const FARMER_LIST_FAIL = 'FARMER_LIST_FAIL'

export const FARMER_DETAILS_REQUEST = 'FARMER_DETAILS_REQUEST'
export const FARMER_DETAILS_SUCCESS = 'FARMER_DETAILS_SUCCESS'
export const FARMER_DETAILS_FAIL = 'FARMER_DETAILS_FAIL'

export const FARMER_PRODUCTS_REQUEST = 'FARMER_PRODUCTS_REQUEST'
export const FARMER_PRODUCTS_SUCCESS = 'FARMER_PRODUCTS_SUCCESS'
export const FARMER_PRODUCTS_FAIL = 'FARMER_PRODUCTS_FAIL'