const products = [
  {
    _id: '1',
    name: 'Banana',
    image: '/images/product-1.jpg',
    description: 'Banana',
    category: 'Fruit',
    price: 20,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Tomato',
    image: '/images/product-2.jpg',
    description: 'Tomato',
    category: 'Vegetable',
    price: 20.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Orange',
    image: '/images/product-3.jpg',
    description: 'Orange',
    category: 'Fruit',
    price: 50.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Rice',
    image: '/images/product-4.jpg',
    description: 'Rice',
    category: 'Cereal',
    price: 199.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Grapes',
    image: '/images/product-5.jpg',
    description: 'Grapes',
    category: 'Fruit',
    price: 25.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Almonds',
    image: '/images/product-6.jpg',
    description: 'Almonds',
    category: 'Nut',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

export default products
